[world]
name = "Dosis"
description = "Dosis Game."
seed = "dosis_game"

[world.socials]
x = ""
github = ""
# discord = ""
# telegram = ""

[namespace]
default = "dosis_game"

[env]
chain_id = "KATANA_LOCAL"
rpc_url = "http://localhost:5050"
account_address = ""
private_key = ""
world_address = ""
world_block = 1

[writers]
"dosisgame" = ["dosis_game"]
