[world]
name = "Dosis"
description = "Dosis Game."
seed = "dosis_game"

[world.socials]
x = ""
github = ""
# discord = ""
# telegram = ""

[namespace]
default = "dosis_game"

[env]
chain_id = "SN_SEPOLIA"
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
# account_address = ""  # env: DOJO_ACCOUNT_ADDRESS
# private_key = ""      # env: DOJO_PRIVATE_KEY
world_address = ""
world_block = 0

[writers]
"dosis_game" = ["dosis_game-game"]