#--------------------------
# Package declaration
#--------------------------
[package]
name = "dosis_game"
version = "1.0.0"
cairo-version = "=2.12.2"
edition = "2024_07"

#--------------------------
# Cairo declaration
#--------------------------
[cairo]
sierra-replace-ids = true

#--------------------------
# Scripts
#--------------------------
[scripts]
migrate = "./migrate"

#--------------------------
# Dependencies
#--------------------------
[dependencies]
starknet = "2.12.2"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.4" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.4" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
dosis_nft = { path = "../dosis_nft" }

#--------------------------
# Starknet contract declaration
#--------------------------
[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world"
]

#--------------------------
# Dev dependencies
#--------------------------
[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.4" }

#--------------------------
# Dojo profiles declaration
#--------------------------
[profile.dev]
[profile.sepolia]
[profile.mainnet]