# torii config for profile [sepolia]

world_address = ""
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[events]
raw = true

[sql]
historical = []

[indexing]
pending = true
transactions = false
world_block =     # Dosis sepolia deployment block
contracts = [
  "erc721: ", # Dosis NFT
]