# World Address to index
world_address = ""

# RPC URL
# Change to mainnet
rpc = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_8"

# Change to sepolia
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true

[server]
http_cors_origins = ["*"]
